version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Berlin
    labels: []
    open-pull-requests-limit: 30
    ignore:
      - dependency-name: "node"
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "vuex"
        update-types: ["version-update:semver-major"]
    groups:
      unhead:
        patterns:
          - "@unhead*"
      lodash:
        patterns:
          - "lodash*"
      vitest:
        patterns:
        - "vitest"
        - "@vitest/*"
      types:
        patterns:
          - "@types*"
        update-types:
          - "patch"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "[BUILD] "
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
